### ISSUE TITLE
"TypeError: Cannot read property 'viewToModelUpdate' of undefined" in igCombo's selectionChanged event

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular-wrappers#244]
### Description  
"TypeError: Cannot read property 'viewToModelUpdate' of undefined" occurs when igCombo's selectionChanged event is fired.

### Steps to reproduce  

1. Unzip the attached file.

2. Under the my-app2 folder,
`>npm install`
`>npm install @infragistics/ignite-ui-full`
`>npm install igniteui-angular-wrappers`
`>npm start`

3. Click on the combo to open the drop down.

4. Select one of the items.

### Result  
In browser's developer tool console:
1440 ERROR TypeError: Cannot read property 'viewToModelUpdate' of undefined
    at HTMLInputElement.eval (webpack-internal:///../../../../igniteui-angular-wrappers/bundles/igniteui-angular-wrappers.umd.js:18613:29)
    at HTMLInputElement.dispatch (http://code.jquery.com/jquery-1.11.3.min.js:4:8549)
    at HTMLInputElement.r.handle (http://code.jquery.com/jquery-1.11.3.min.js:4:5252)
    at Object.trigger (http://code.jquery.com/jquery-1.11.3.min.js:4:7650)
    at HTMLInputElement.<anonymous> (http://code.jquery.com/jquery-1.11.3.min.js:4:15517)
    at Function.each (http://code.jquery.com/jquery-1.11.3.min.js:2:2975)
    at m.fn.init.each (http://code.jquery.com/jquery-1.11.3.min.js:2:835)
    at m.fn.init.trigger (http://code.jquery.com/jquery-1.11.3.min.js:4:15493)
    at e.(anonymous function).(anonymous function)._trigger (http://code.jquery.com/ui/1.11.1/jquery-ui.min.js:6:12975)
    at e.(anonymous function).(anonymous function)._triggerSelectionChanged (http://cdn-na.infragistics.com/igniteui/2017.2/latest/js/infragistics.lob.js:28:22807)

### Expected result  
No such errors.

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
[my-app2.zip](https://github.com/IgniteUI/igniteui-angular-wrappers/files/1645619/my-app2.zip)

**Comment by damyanpetev** [comment]
@norikois Seems to be because the combo isn't bound via `ngModel` yet. Goes away after you bind it to a property (e.g. `[(ngModel)]="comboValue"`, requires Angular's `FormsModule`).
P.S. That likely means the `comboSelectionChangedHandler` is not required 😉 

The problem is with this [check](https://github.com/IgniteUI/igniteui-angular-wrappers/blob/244824a18d1f10ec613cd82d0821cc794db5241a/src/igcombo/igcombo.component.ts#L32), but really the whole internal selection changed handler should be under the model check few lines below it.
